apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.odooApp.name }}-backup-pvc
  namespace: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.odooDB.backup.volume.size }}
  storageClassName: azurefile-csi
