apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-backup-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.odooDB.backup.volume.accessModes }}
  volumeMode: {{ .Values.odooDB.backup.volume.volumeModes }}
  resources:
    requests:
      storage: {{ .Values.odooDB.backup.volume.size }}
  storageClassName: {{ .Values.odooDB.backup.volume.type }}
