apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.odooDB.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{ .Values.odooDB.labels.key }}: {{ .Values.odooDB.labels.value }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
