apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.odooDB.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ required "Postgres user is required!" .Values.odooDB.credentials.user | b64enc }}
  POSTGRES_PASSWORD: {{ required "Postgres user's password is required!" .Values.odooDB.credentials.password | b64enc }}
  POSTGRES_DB: {{ required "Database name is required!" .Values.odooDB.credentials.database | b64enc }}
