apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.odooApp.name }}
  namespace: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.odooApp.name }}-{{ .Release.Name }}.sla686-avoin-assignment.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.odooApp.name }}
                port:
                  number: 80
