apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.odooApp.name }}
  namespace: {{ .Release.Name }}
spec:
  selector:
    {{ .Values.odooApp.labels.key }}: {{ .Values.odooApp.labels.value }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8069
