# This workflow will build and push an application to a Azure Kubernetes Service (AKS) cluster when you push your code
#
# This workflow assumes you have already created the target AKS cluster
#
# To configure this workflow:
# 1. Set the following secret in your repository:	
#    - KUBE_CONFIG	
#
# 2. Choose the appropriate render engine for the bake step https://github.com/Azure/k8s-bake. The config below assumes Helm.
#    Set your helmChart, overrideFiles, and helm-version to suit your configuration.
#    - CHART_PATH (path to your helm chart)
#    - CHART_OVERRIDE_PATH (path to your helm chart with override values)
#    - HELM_VERSION

name: Build and deploy an app to AKS with Helm

on:
  push:
    branches: ["master"]
    
env:

  CHART_PATH: "."
  CHART_OVERRIDE_PATH: "."
  HELM_VERSION: latest

jobs:
  helm:
    name: Helm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@main
        
      - name: Set context
        uses: Azure/k8s-set-context@v2
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Lint chart
        run: helm lint ${{ env.CHART_PATH }}
        working-directory: ${{ env.CHART_PATH }}

      - name: Install release
        uses: hiberbee/github-action-helm@latest
        with:
          helm: upgrade --install --dry-run ${{ github.ref_name }} ${{ env.CHART_PATH }}
          
      - name: Install Helm chart
        uses: azure/k8s-bake@v2.2
        with:
          renderEngine: 'helm'
          helmChart: ${{ env.CHART_PATH }}
          overrideFiles: ${{ env.CHART_OVERRIDE_PATH }}
          helm-version: ${{ env.HELM_VERSION }}
